# Generated by Django 3.2.15 on 2022-08-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineClassRoom',
        ),
    ]
